spring.application.name=demo
#spring.ai.openai.api-key=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
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile